version: '3.8'
services:
  dev-db:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: strapi
      POSTGRES_USER: strapi
      POSTGRES_PASSWORD: strapi
    volumes:
      - ./data:/var/lib/postgresql/data